### ISSUE TITLE
Update pdidev website for github's main branch

### ISSUE THREAD

**Issue by benoitmartin88** [pdidev/pdidev.github.io#1]
website still points to gitlab

**Comment by jbigot** [comment]
The sources have been fixed. The issue is one of deployment. [Our script](https://github.com/pdidev/pdidev.github.io/blob/main/.github/actions/deploy/entrypoint.sh) still downloads the sources from gitlab.

**Comment by jbigot** [comment]
Also, we need a trigger from commit in PDI main to the website repo

**Comment by benoitmartin88** [comment]
We are waiting for release 1.8.0 to retrieve the generated documentation artifact.

**Comment by jbigot** [comment]
The doc for main could already be fetched from github
